import 'dart:convert';
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:uasricky/model/model.dart';
import 'package:uasricky/providers/providers.dart';

void main() {
  runApp(new MaterialApp(home: new HomePage()));
}

class HomePage extends StatefulWidget {
  @override
  HomePageState createState() => new HomePageState();
}

class HomePageState extends State<HomePage> {
  Future<List<Autogenerated>> datas = getData();

  @override
  Widget build(BuildContext context) => Scaffold(
      appBar: AppBar(
        title: const Text("UAS - Ricky Ahmad Ika Marhaendra - 191011401516"),
        centerTitle: true,
      ),
      body: Center(
        child: FutureBuilder<List<Autogenerated>>(
          future: datas,
          builder: (context, snapshot){
            if(snapshot.hasData){
              final data = snapshot.data!;
              return buildData(data);
            }else{
              return const Text("Error");
            }
          },
        ),
      ),
  );

  Widget buildData(List<Autogenerated> dataJs) => ListView.builder(
    itemCount: dataJs.length,
    itemBuilder: (context, index) {
      final dataj = dataJs[index];

      String bodyData = 'id : '+dataj.id.toString()+' \nbody : ' + dataj.body + ' \nuserid : ' + dataj.userId.toString();

      return Card(
        child: ListTile(
          title: Text(dataj.title),
          subtitle: Text(bodyData),
        ),
      );
    },
  );
}
